Add core files.
digitalbazaar/bedrock-authn-did-jwt pull request #1
Opened 2016-12-12 18:28 UTC by mattcollier

2017-01-06 19:58 UTC, dlongley requested changes
We need a little bit of redesign, it will be easier if we hash it out elsewhere.

2017-01-06 19:58 UTC, dlongley commented on lib/index.js
> +var jwtOptions = {
This should not be module global, but rather strategy-instance specific.

2017-01-11 16:34 UTC, mattcollier commented
@dlongley ready for another pass.

2017-01-11 17:38 UTC, dlongley requested changes

2017-01-11 17:38 UTC, dlongley commented on lib/DidJwtStrategy.js
> +    throw v.error;
While I like the idea of using the validation library here, I think it's a little weird and out of place. I think most people would be expecting to see `TypeError`s for misuse of the API. This also breaks with our code everywhere else that we handle JS API errors. I think we should change this to the usual style:

```js
options = options || {};
if(typeof options.foo !== 'string') {
  throw new TypeError('options.foo must be a string.');
}
// ...
```

2017-01-11 17:38 UTC, dlongley commented on lib/DidJwtStrategy.js
> +    if(!('urn:bedrock.authn' in decoded)) {
This name `urn:bedrock.authn` is weird. Since this is a closed system, let's just use `bedrock-authn-did` and just set it equal to the DID value.

2017-01-11 17:38 UTC, dlongley commented on lib/DidJwtStrategy.js
> +        'Token is missing DID.', 'InvalidToken'));
`Token is missing DID` => `Invalid decentralized identifier.`

2017-01-11 17:38 UTC, dlongley commented on lib/index.js
> +const STORE_NAME_SPACE = 'authn-did-jwt';
=> `STORE_NAMESPACE`

2017-01-11 17:38 UTC, dlongley commented on lib/index.js
> +  app.get(routes.token, ensureAuthenticated, (req, res, next) => {
`HTTP GET` should be idempotent. Will discuss w/you.

2017-01-11 17:38 UTC, dlongley commented on lib/DidJwtStrategy.js
> +    token: req.body.token
There is a standard for JWT authentication that uses the `Authorization: Bearer <token>` HTTP header. We should follow this pattern unless we've got a good reason not to.

2017-01-11 17:38 UTC, dlongley commented on lib/index.js
> +      'Invalid DID specified.', 'InvalidDid',
`Invalid decentralized identifier specified.`

2017-01-11 18:05 UTC, mattcollier commented on lib/DidJwtStrategy.js
> +    throw v.error;
I agree that the validation library seems like a good fit.  Are there modifications we can make to the error returned by validation or a new API that would bring it in line.

The validation library seems like the right tool to use rather that writing a bunch of validation code for N parameters.

2017-01-11 18:07 UTC, mattcollier commented on lib/DidJwtStrategy.js
> +    token: req.body.token
In our current use case, the front end receives the token in the URL, then it makes a post request putting the token in the body.  Would you like the front end to put the token in a header instead?

2017-01-15 20:42 UTC, mattcollier commented
Implemented in a different branch.

2017-01-15 20:42 UTC, closed without merging